### ISSUE TITLE
Logo Design: CameraRecorder

### ISSUE THREAD

**Issue by baranpirincal** [MasayukiSuda/CameraRecorder-android#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by MasayukiSuda** [comment]
That sounds great. Would love to set a logo that goes with the concept!

**Comment by baranpirincal** [comment]
@MasayukiSuda 

Can I see interface of application? Also, if you have an idea about design decision please feel free to share with me.

Best Regards
Baran Pirinçal

**Comment by MasayukiSuda** [comment]
I'm not a very design-oriented person. Most probably my suggestions will be a hindrance. So go for it as you see fit.

**Comment by baranpirincal** [comment]
Hey again!

Here is my logo design. 

I want to get feedback from you.

Best Regards
Baran Pirinçal

![untitled-1](https://user-images.githubusercontent.com/37786733/42728517-99147fc4-87c4-11e8-8645-60de63098f48.jpg)

**Comment by MasayukiSuda** [comment]
Thanks great design !!

**Comment by baranpirincal** [comment]
@MasayukiSuda

You're welcome!

I will do some last arrangements and after that I will share with you.

Best Regards
Baran Pirinçal

**Comment by baranpirincal** [comment]
Hey again @MasayukiSuda ,

I have finished the last regulations.

changes are:

- strokes thicker and equal
- bigger video film appearance
- application icon
- logotype version alternatives.

I will create a pull-request and upload all necessary files as soon as possible! :)

#### Best Regards
#### Baran Pirinçal


![saaq](https://user-images.githubusercontent.com/37786733/42887239-26d19338-8aae-11e8-964c-da9e6dba1f68.jpg)

**Comment by baranpirincal** [comment]
![camera-recorder-mockup](https://user-images.githubusercontent.com/37786733/42894067-93e61308-8abe-11e8-8245-ddf00080c71b.jpg)

**Comment by MasayukiSuda** [comment]
Thanks !!
