### ISSUE TITLE
The preview become smaller n Samsung s6

### ISSUE THREAD

**Issue by stonyz** [MasayukiSuda/CameraRecorder-android#13]
Reproduce steps,
1. select any filter firstly
2. start recording
3. the preview image become smaller

**Comment by MasayukiSuda** [comment]
Set video size

**Comment by stonyz** [comment]
I have set,  actually I run the sample directly.  it works fine on others devices , only on Samsung S6.

I debug it, once I remove the line in EncodeRenderHandler, the preview doesn't become small, but the video will not be created.   I don't know how the line effect the preview.

```
   glFilter.draw(filterFramebufferObject.getTexName(), framebufferObject);
```
