### ISSUE TITLE
while Playing Recorded Video it shows first frame of video only 

### ISSUE THREAD

**Issue by mubarak1361** [MasayukiSuda/CameraRecorder-android#18]
while Playing Recorded Video it shows first frame of video only

**Comment by rajivbkulshreshtha** [comment]
I was also getting the same issue, So make sure that permissions for `android.permission.CAMERA`, `android.permission.WRITE_EXTERNAL_STORAGE`, `android.permission.RECORD_AUDIO` are granted

**Comment by MasayukiSuda** [comment]
@rajivbkulshreshtha thx!!
