### ISSUE TITLE
Mp4 to HLS Stream Problem with pts_delta

### ISSUE THREAD

**Issue by knowamit** [MasayukiSuda/CameraRecorder-android#19]
Hi I am trying to convert the video in to hls but audio is not clear after convert into hls. 
Observed that there is some problem in encoding the video as the data is 
pts      dts      diff  frame  size  total   pts_delta
-1024    -1024    0     1      23    23      
0        0        0     2      423   446     1024
1812     1812     0     3      424   870     1812
2449     2449     0     4      414   1284    637
3341     3341     0     5      405   1689    892
4123     4123     0     6      357   2046    782
5091     5091     0     7      399   2445    968
6890     6890     0     8      384   2829    1799
7793     7793     0     9      366   3195    903
8519     8519     0     10     391   3586    726
9490     9490     0     11     372   3958    971
10603    10603    0     12     369   4327    1113
11350    11350    0     13     703   5030    747
12935    12935    0     14     313   5343    1585
13877    13877    0     15     325   5668    942
14823    14823    0     16     323   5991    946
15677    15677    0     17     322   6313    854
16542    16542    0     18     327   6640    865
17358    17358    0     19     333   6973    816
19304    19304    0     20     347   7320    1946
19992    19992    0     21     357   7677    688
20945    20945    0     22     405   8082    953
21739    21739    0     23     421   8503    794
22748    22748    0     24     441   8944    1009
23878    23878    0     25     445   9389    1130

As a comparison, here's an example from another input with expected values:
pts      dts      diff  frame  size  total   pts_delta
164      -1600    1764  1      364   364     
1188     -576     1764  2      365   729     1024
2212     448      1764  3      384   1113    1024
3236     1472     1764  4      398   1511    1024
4260     2496     1764  5      409   1920    1024
5284     3520     1764  6      400   2320    1024
6308     4544     1764  7      388   2708    1024
7332     5568     1764  8      397   3105    1024
8356     6592     1764  9      391   3496    1024
9380     7616     1764  10     379   3875    1024

please help me regarding this issue

**Comment by MasayukiSuda** [comment]
It has nothing to do with this library

**Comment by amitsharma492** [comment]
it might be related to this lib because video recorded with this lib is making the issue. Might be some issue in VideoEncoder and AudioEncoder. please check
