### ISSUE TITLE
Overlay filter crashes app in sample app

### ISSUE THREAD

**Issue by khurana3192** [MasayukiSuda/CameraRecorder-android#3]
First of all, many thanks for developing this library.

There was a huge need for someone to pick up the dirty work and that too with filters

I notice that when you select overlay filter in sample app, the app crashes.

I am using Android 8.1 on an Android one device - Xiaomi mi A1

**Comment by MasayukiSuda** [comment]
Thanks. I fixed.

**Comment by khurana3192** [comment]
Can you please take out some time and update the README about what Overlay does.
The documentation is quite confusing at the moment.
