### ISSUE TITLE
Filter Previews

### ISSUE THREAD

**Issue by khurana3192** [MasayukiSuda/CameraRecorder-android#4]
I am trying to set few FrameLayouts at bottom of my Camera Preview Frame Layout, to show filter previews for different filters (Like Instagram)

How should I make sure that these mini Frame Layouts can show different Filter Previews for different filters.

At the moment, setFiler() method works on cameraRecorder

How to make sure it changes previews of mini FrameLayouts.

Any help in this regard?

**Comment by MasayukiSuda** [comment]
It has nothing to do with this library.

**Comment by khurana3192** [comment]
@MasayukiSuda 
I totally understand your point that this is beyond the scope of this library.
I was following your sample app and was super impressed.
I need to know if these filters can be previewed in multiple layouts.
Your current method works on cameraRecorder instance.
Is there an internal method I can call to preview it in a different view?

**Comment by khurana3192** [comment]
Can you please help me achieve this?
